### ISSUE TITLE
Load CRIC with the computing sites

### ISSUE THREAD

**Issue by StevenCTimm** [DUNE/dist-comp#1]
XML of the OSG Factory is at https://github.com/opensciencegrid/osg-gfactory.git

As parsed for the vo-feed is found at http://dune-data.fnal.gov/vofeed/vofeed.xml

**Comment by StevenCTimm** [comment]
This appears to be almost done.

**Comment by Andrew-McNab-UK** [comment]
Done. Fine tuning on https://github.com/DUNE/dist-comp/issues/10
