### ISSUE TITLE
Glideins running at UK_Durham but not matching

### ISSUE THREAD

**Issue by StevenCTimm** [DUNE/dist-comp#101]
we are submitting glideins there but they are never starting for last 19 days, why?

**Comment by StevenCTimm** [comment]
Still active, filed GGUS ticket, no response.

**Comment by adamboutcher** [comment]
> Still active, filed GGUS ticket, no response.
> 

I don't think the ggus ticket has hit us... I've been on leave so I'm not 100% sure.

**Comment by StevenCTimm** [comment]
https://ggus.eu/index.php?mode=ticket_info&ticket_id=164299

**Comment by adamboutcher** [comment]
So we think this may be resolved as the voms ca had changed and we didn't realise.

**Comment by StevenCTimm** [comment]
Not fixed yet.. site has been offline since well before the voms CA changed.. but by the way did you get the communication that voms2.fnal.gov.lsc also changed yesterday.

**Comment by StevenCTimm** [comment]
Glideins are running but as far as we can tell still not matching any jobs.

**Comment by StevenCTimm** [comment]
This was fixed quite some time ago, not sure how or when.
