### ISSUE TITLE
Make benchmarks for HEPScore

### ISSUE THREAD

**Issue by StevenCTimm** [DUNE/dist-comp#11]
Need to identify a workload to put in a container.

**Comment by Andrew-McNab-UK** [comment]
From Slack: "Heidi Schellman  3:07 PM @Andrew McNab @kherner @tomjunk put a benchmark in dunegpvm07.fnal.gov:/dune/data/users/schellma/benchmark.tar.gz (also in directory benchmark)"

**Comment by StevenCTimm** [comment]
We have the candidate benchmark and Nagaraj has run it at INFN.. still have to work with the benchmark deployment Taskforce (hepix / Michel Jouvin) to determine common form of packaging for DUNE + the WLCG experiments.

**Comment by Andrew-McNab-UK** [comment]
Example HEP workloads and outline of the procedure: https://gitlab.cern.ch/hep-benchmarks/hep-workloads
