### ISSUE TITLE
Transition the ETF Testing to use the CRIC for input

### ISSUE THREAD

**Issue by StevenCTimm** [DUNE/dist-comp#12]

**Comment by rajanandakumar** [comment]
From Marian Babik -
Provided a valid DUNE feed is served by CRIC, there is just one file that needs to be updated: 
https://gitlab.cern.ch/etf/etf-dune/-/blob/master/config/ncgx.cfg
 (URL listed under PLUGINS attribute needs to be updated to point to CRIC feed, which can be done by anyone who can commit)

**Comment by StevenCTimm** [comment]
Done!
