### ISSUE TITLE
Why DUNE_IT_INFN_CNAF not getting tested in AWT

### ISSUE THREAD

**Issue by StevenCTimm** [DUNE/dist-comp#123]
it shows as enabled but no testing is happening.

**Comment by StevenCTimm** [comment]
The isTape field wasn't set.  I have set it now to false.  That should help

**Comment by Andrew-McNab-UK** [comment]
It's not being included because it does not offer root as a read protocol.

**Comment by Andrew-McNab-UK** [comment]
The site IT_CNAF is not set for this RSE either. Could you add that too? Thanks

**Comment by StevenCTimm** [comment]
I've added the IT_CNAF site tag to it.
They only support davs right now.. we can go back to them eventually and see if they will support xrootd.

**Comment by Andrew-McNab-UK** [comment]
This came up at the CRAB and we've been asked to pursue it. So we should approach them again about xroot streaming in jobs.

**Comment by StevenCTimm** [comment]
This has all been done.. xrootd streaming is working the site label is there, now we need to start testing it.
I have already enabled it in rucio and JustIN.

**Comment by StevenCTimm** [comment]
it's being tested now and passing.
