### ISSUE TITLE
All AWT writes to MANCHESTER and QMUL failing with error code 99

### ISSUE THREAD

**Issue by StevenCTimm** [DUNE/dist-comp#130]
Normally we would look at the wrapper job log to see where these are failing 
but none of the logs are available for whatever reason.  see 

https://justin.dune.hep.ac.uk/dashboard/?method=show-job&jobsub_id=174550.0@justin-prod-sched01.dune.hep.ac.uk

the stderr that would normally be there, isn't there.

**Comment by wyuan-uoe** [comment]
Manchester can work when I xrdcp or gfal-copy to MANCHESTER.

I'll issue a ticket to QMUL.

**Comment by Andrew-McNab-UK** [comment]
Looks like this was resolved by fixing #131

**Comment by StevenCTimm** [comment]
yes qmul working again too, they answered the ticket.
