### ISSUE TITLE
Modify the rucio/metacat upload in justIN to populate the DID's into the metacat dataset that is created.

### ISSUE THREAD

**Issue by StevenCTimm** [DUNE/dist-comp#133]
justIn was recently modified to include the creation of a metacat dataset with matching name to the rucio dataset.
We would now like to populate that metacat dataset with the same DID's that exist in the rucio dataset, as it is filled.

**Comment by Andrew-McNab-UK** [comment]
When during the output phase of the job do you want the files to be added to the MetaCat dataset? Before or after the Rucio upload of that file? Or of all the files in from that job? The timing of this affects what is left in MetaCat when the uploads go wrong.

**Comment by StevenCTimm** [comment]
This is indeed a critical issue.. in fact in recent production we also had problems in case that the rucio DID was created but the upload never finished and no uploads were created.

The initial declaration of the file into metacat (as part of the dune:all dataset) is done before the rucio upload is
even attempted and then it is updated when the upload is "confirmed"
This seems like a good time to insert it into the corresponding named metacat dataset as well.

**Comment by Andrew-McNab-UK** [comment]
This is included in 01.01
