### ISSUE TITLE
Request that workflow_id be promoted to be a searchable key in the workflow metacat

### ISSUE THREAD

**Issue by hschellman** [DUNE/dist-comp#136]
Workflow_id (and likely stage_id) turns out to be a very useful item which is very hard to get at because it is in a dictionary not a field in metacat.  

Can we do this:

"dune.workflow": {
            "cpuinfo": "Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz",
            "hostname": "b9g37p4324.cern.ch",
            "job_id": "159542.148@justin-prod-sched01.dune.hep.ac.uk",
            "jobscript_cpu_seconds": 730,
            "jobscript_finish": 1708383531,
            "jobscript_real_seconds": 941,
            "jobscript_start": 1708382589,
            "os_release": "Scientific Linux release 7.9 (Nitrogen)",
            "site_name": "CERN",
            _#"stage_id": 1,_
            "user": "benjamin@fnal.gov",
           _# "workflow_id": 1590_
        },

"dune.workflow.workflow_id":1590
"dune.workflow.state_id":1,

so that the syntax for searches is easier (and likely much faster)

Thanks, Heidi

**Comment by Andrew-McNab-UK** [comment]
IMO there isn't really a problem with the syntax for searching for things in dictionaries:

`metacat query 'files from dune:all where dune.workflow["workflow_id"]=1633 and dune.output_status="confirmed"'`

and it avoids an explosion in the size of the top level and the need to find unique names for all the keys.

I think the question really is what the irreducible performance implications are: are they unreasonably slow and if so, is there a reason why the MetaCat database cannot support efficient queries on them?

**Comment by Andrew-McNab-UK** [comment]
From schema.sql, MetaCat stores the whole metadata dictionary for each file as a postgreSQL jsonb type, and creates a GIN index on the whole lot. This is supposed to be efficient and does not need lots of parsing as the JSON is precompiled into a fast binary format when each row is added.

**Comment by hschellman** [comment]
I’m not really asking about performance, things like the dataset creator have to be hacked to take that kind of syntax where it is trivial to parse and use a key=Y directive because it is like all the others.

And it doesn’t work at all with samweb.

End users would definitely find the key=X syntax easier than a new  key[‘x’] in (Y). syntax.

I’m not asking for all of those fields - just the ones that would be used in searches.   The rest are there to store useful data, but the workflow id is really useful in searches.

I’ve already run into the fact that one can’t generate a samweb query without hacking in that key =Y format.


On Mar 2, 2024, at 2:55 PM, Andrew McNab ***@***.***> wrote:


[This email originated from outside of OSU. Use caution with links and attachments.]


IMO there isn't really a problem with the syntax for searching for things in dictionaries:

metacat query 'files from dune:all where dune.workflow["workflow_id"]=1633 and dune.output_status="confirmed"'

and it avoids an explosion in the size of the top level and the need to find unique names for all the keys.

I think the question really is what the irreducible performance implications are: are they unreasonably slow and if so, is there a reason why the MetaCat database cannot support efficient queries on them?

**Comment by hschellman** [comment]
And to be precise:  Our CDR states that

"MetaCat attributes are name-value pairs”

Users generally expect to be able to use x.y=Y syntax in queries, the exception being run-numbers.

So this is a request to conform to the expectation for things one will be querying.



On Mar 2, 2024, at 4:37 PM, Heidi Schellman ***@***.***> wrote:


[This email originated from outside of OSU. Use caution with links and attachments.]

I’m not really asking about performance, things like the dataset creator have to be hacked to take that kind of syntax where it is trivial to parse and use a key=Y directive because it is like all the others.

And it doesn’t work at all with samweb.

End users would definitely find the key=X syntax easier than a new key[‘x’] in (Y). syntax.

I’m not asking for all of those fields - just the ones that would be used in searches. The rest are there to store useful data, but the workflow id is really useful in searches.

I’ve already run into the fact that one can’t generate a samweb query without hacking in that key =Y format.


On Mar 2, 2024, at 2:55 PM, Andrew McNab ***@***.***> wrote:


[This email originated from outside of OSU. Use caution with links and attachments.]


IMO there isn't really a problem with the syntax for searching for things in dictionaries:

metacat query 'files from dune:all where dune.workflow["workflow_id"]=1633 and dune.output_status="confirmed"'

and it avoids an explosion in the size of the top level and the need to find unique names for all the keys.

I think the question really is what the irreducible performance implications are: are they unreasonably slow and if so, is there a reason why the MetaCat database cannot support efficient queries on them?

**Comment by Andrew-McNab-UK** [comment]
The CDR says: "Metadata attributes are name-value pairs. ...  Attribute names are alphanumeric words optionally combined with dots. **Any JSON structure can be an attribute value**"

I think this removing this flexibility would be a long term loss for very short term gains - mostly about not changing from how SAM does it. 

Anything worth storing is going to be searched for by someone. So we will end up promoting everything to the top level. 

Furthermore, users and applications are going to want to store their own metadata. IMO it's much better to say to them "put your specific stuff in a dictionary", but if we're not having dictionaries because people will want to search that metadata as well, that goes in the top level too. 

I don't really see that `dune.workflow["workflow_id"]=1633` is harder to understand than `dune.workflow.workflow_id=1633` To a new user, it just looks like Python syntax. To people used to SAM, well, yes, it's not SAM and there are going to be differences. But from our point of view there are major gains.

**Comment by hschellman** [comment]
I’m not requesting that all of the info from the workflow be changed, just the 2 that are very useful. I agree strongly that the json format for the rest of the workflow info is very helpful.

SO no request not to do the dictionaries, just a request for that particular field.

On Mar 2, 2024, at 5:26 PM, Andrew McNab ***@***.***> wrote:


[This email originated from outside of OSU. Use caution with links and attachments.]


The CDR says: "Metadata attributes are name-value pairs. ... Attribute names are alphanumeric words optionally combined with dots. Any JSON structure can be an attribute value"

I think this removing this flexibility would be a long term loss for very short term gains - mostly about not changing from how SAM does it.

Anything worth storing is going to be searched for by someone. So we will end up promoting everything to the top level.

Furthermore, users and applications are going to want to store their own metadata. IMO it's much better to say to them "put your specific stuff in a dictionary", but if we're not having dictionaries because people will want to search that metadata as well, that goes in the top level too.

I don't really see that dune.workflow["workflow_id"]=1633 is harder to understand than dune.workflow.workflow_id=1633 To a new user, it just looks like Python syntax. To people used to SAM, well, yes, it's not SAM and there are going to be differences. But from our point of view there are major gains.

**Comment by Andrew-McNab-UK** [comment]
The workflow ID has been used in MetaCat searches and performance testing of dictionaries shows that this format is ok.

**Comment by hschellman** [comment]
Can you document the way the search is done so we have a record?

On Jun 11, 2024, at 11:57 AM, Andrew McNab ***@***.***> wrote:


[This email originated from outside of OSU. Use caution with links and attachments.]


Closed #136<https://github.com/DUNE/dist-comp/issues/136> as completed.
