### ISSUE TITLE
Get ETF and CRIC url's into the standing meeting agenda

### ISSUE THREAD

**Issue by StevenCTimm** [DUNE/dist-comp#14]

**Comment by rajanandakumar** [comment]
CRIC URL : https://dune-cric.cern.ch/core/experimentsite/list/

ETF URL : https://etf-dune-preprod.cern.ch/etf/check_mk/index.py?start_url=%2Fetf%2Fcheck_mk%2Fview.py%3Fview_name%3Dallhosts

**Comment by StevenCTimm** [comment]
Raja is there also a place in Monit where this stuff is plotted.

Steve

________________________________

**Comment by rajanandakumar** [comment]
https://monit-grafana.cern.ch/d/eljk1MiMz/wlcg-sitemon-historical-tests-qa?orgId=20&var-vo=dune

But I believe history in a graph is not available as yet - Maybe Marian Babik or Borja Garrido Bear will know. When I last asked, it needed some development from the monit people.

**Comment by rajanandakumar** [comment]
Just got an update that the timeline information is already available now

https://monit-grafana.cern.ch/d/eljk1MiMz/wlcg-sitemon-historical-tests-qa?orgId=20&var-vo=dune

Cheers,
Raja.

**Comment by Andrew-McNab-UK** [comment]
I think both of these are moot points at the moment.
