### ISSUE TITLE
JustIN apparently marking large fractions of jobs stalled when it should not be

### ISSUE THREAD

**Issue by StevenCTimm** [DUNE/dist-comp#156]
It's not clear if this is a HTCondor issue or a JustIN issue, but investigation shows that 90-95% of the jobs that JustIN is marking as "stalled" in fact are running to completion.  More investigation is needed to see why.

**Comment by Andrew-McNab-UK** [comment]
This was a transitory problem with the HTCondor schedds overloaded compounded by faulty checking of HTCondor return codes which was fixed in 01.01
