### ISSUE TITLE
Need better error messages when making workflow requests

### ISSUE THREAD

**Issue by calcuttj** [DUNE/dist-comp#157]
When giving bad arguments i.e. nonexistent scopes to justin, it just responds with an HTTP error and not something immediately helpful

<pre>
workflow$ justin simple-workflow --jobscript april2024_PDHD_dress_rehearsal.jobscript  \
--mql "files from dune:all where dune.workflow['workflow_id'] in (1757) and core.data_tier=full-reconstructed and dune_mc.space_charge=yes and core.event_count=10 limit 1000" \
--env NEVENTS=1  --env "DR_DIR=${DR_DIR}" \
<b>--scope usertest</b> --max-distance 30 --rss-mb 5500 --wall-seconds 1800 \
--lifetime-days 7 \
--output-pattern "*rerun_reco.root:april_pdhd_dress_rehearsal_reco_test_00"
<b>Connection error: HTTP Error 500: Internal Server Error</b>
</pre>

<pre>
workflow$ justin simple-workflow --jobscript april2024_PDHD_dress_rehearsal.jobscript \
--mql "files from dune:all where dune.workflow['workflow_id'] in (1757) and core.data_tier=full-reconstructed and dune_mc.space_charge=yes and core.event_count=10 limit 1000" \
--env NEVENTS=1  --env "DR_DIR=${DR_DIR}"   \
<b>--scope usertests</b> --max-distance 30 --rss-mb 5500 --wall-seconds 1800 \
--lifetime-days 7 \
--output-pattern "*rerun_reco.root:april_pdhd_dress_rehearsal_reco_test_00"
<b>1807</b>
</pre>

**Comment by Andrew-McNab-UK** [comment]
This is fixed in 01.01.00
