### ISSUE TITLE
Documentation updates

### ISSUE THREAD

**Issue by hschellman** [DUNE/dist-comp#166]
Now that we have to run in containers, some questions about updating documentation.

Should we add starting an Apptainer to the startup comments for Justin?

Do tokens work?  Should we point to token as well as proxy authentication? 

I'm trying to update the main tutorials and should be able to provide links.

**Comment by StevenCTimm** [comment]
straight Justin commands can be run outside of the container in python3.9/alma9.. haven't tried the other side.
All JustIN auth has been via token from the beginning, it has never used X.509.

**Comment by Andrew-McNab-UK** [comment]
There is a script which does this in cvmfs but it's not documented or officially supported. We should decide more generally what our plan is for providing container starting commands to end users, suitable for gpvm machines and/or private machines. It's at /cvmfs/dune.opensciencegrid.org/products/dune/justin/pro/NULL/bin/justin-sl7-setup But this question is not specific to justIN, as it needs to work for Rucio commands, and the analysis environments.
