### ISSUE TITLE
justIN able to make rules to send datasets to DUNE_US_FNAL_DISK_STAGE

### ISSUE THREAD

**Issue by StevenCTimm** [DUNE/dist-comp#178]
As discussed and agreed in 7/18/24 DUNE production meeting, please re-add the capacity to JustIN to allow the 
transfer to Fermilab DUNE_US_FNAL_DISK_STAGE of output pattern <n>.  This is needed for the keep-up production of protoDUNE.

**Comment by Andrew-McNab-UK** [comment]
This is really going to amount to the general ability to request a rule to be made when creating a dataset, with the Fermilab RSE as one application of that feature.

**Comment by StevenCTimm** [comment]
This now works.  will leave it to Andrew to close.
