### ISSUE TITLE
Display the app version (and possibly app name) on the dashboard.  And possibly take it as an input to specify the job config

### ISSUE THREAD

**Issue by hschellman** [DUNE/dist-comp#179]
It would be very useful to be able to see what jobs are running from the dashboard.

Could the app version be added to the fields one can see?  This helps to tell different jobs apart.   

If we are running production, in fact, the initial job spec should be possibly by setting that version at submission and then letting the job script handle the workflow

example would be

DUNERECO_VERSION=v09_90_01d00

There are likely cases where different parts of the job use different versions but that would be very unfortunate.

**Comment by Andrew-McNab-UK** [comment]
This can already be done by the user giving a description when submitting the workflow. So an option like `--description "Reco with $DUNERECO_VERSION"`. It's also possible to pass environment variables to jobscripts with options like `--env DUNERECO_VERSION="$DUNERECO_VERSION"` which may make it easier to keep things consistent.
