### ISSUE TITLE
Implement command to return query from a given justin workflow 

### ISSUE THREAD

**Issue by calcuttj** [DUNE/dist-comp#180]
This would be useful for makeup workflows. 

i.e. I want to run over the files from a given workflow/query which were not successfully processed, an easy way to do this would be to do the following

<pre>
old_query=`justin show-workflow-query --workflow-id 0001`
justin simple-workflow \
  --mql "$old_query - parents(files from wf0001_scope:wf0001_output where dune.output_status='confirmed')" \
  _other options_
<pre>

**Comment by Andrew-McNab-UK** [comment]
This can be done with `justin show-workflows --workflow-id 0001` but you need to know what your descriptions look like to parse the output reliably. If you have no description, you can just do`justin show-workflows --workflow-id 3927 | cut -d' ' -f8-` I'd like to park this topic for now until I have the retrying of failed files stuff working through the dashboard, as that hopes to address the wider use case and avoid the need for new workflows to try files again.
