### ISSUE TITLE
Site CZ_FZU doesn't show PRAGUE storage element as local

### ISSUE THREAD

**Issue by StevenCTimm** [DUNE/dist-comp#182]
PRAGUE storage element which is at FZU is showing as distance 20
to CZ_FZU.  Should be distance zero.
Looks like this can't be fixed by ordinary Justin admins.
Andrew can you please fix?

**Comment by Andrew-McNab-UK** [comment]
This is happening because the PRAGUE RSE has the attribute "site" set to CZ_Prague (which doesn't exist) rather than CZ_FZU. If you change it in the Rucio config, then justIN will pick it up.

**Comment by StevenCTimm** [comment]
Fixed.. will wait until we see Justin picked it up

**Comment by ahiguera-mx** [comment]
Great, thanks for catching and fixed this @StevenCTimm

**Comment by Andrew-McNab-UK** [comment]
justIN has now picked up the change and has set the distance to be zero between PRAGUE and CZ_FZU.
