### ISSUE TITLE
Follow ISO-8601 for justIN-generated timestamps in filenames.

### ISSUE THREAD

**Issue by kherner** [DUNE/dist-comp#183]
I saw a recent file from a tutorial run and it looks like timestamps get added to outputs of the form

YYYY-mm-ddT_HHMMSSZ.

The canonical ISO-8601 form for UTC is of course

YYYY-mm-ddTHH:MM:SSZ (or a space instead of the T)

But I doubt we want to be putting whitespace or colons in filenames. A valid alternate format is

YYYYmmddTHHMMSSZ

But justIN currently seems to be mixing in hyphens and then (inexplicably to me, at least) adding an underscore, which doesn't correspond with what's been used for far and doesn't seem to follow the usual timestamps standards (also not valid rfc-3339). I don't see any reason not to follow the convention. Also I doubt we need sub-second accuracy in the filenames.

**Comment by Andrew-McNab-UK** [comment]
Yes, this is one of the jobscripts the tutorial refers to, so it's easy to change. I think the timestamps originally came from test POMS workflows! I've changed it to the last format, and that will appear in the next minor release. Thanks!

**Comment by Andrew-McNab-UK** [comment]
Updated example jobscript included in 01.02.rc1
