### ISSUE TITLE
Have Justin set DesiredOS flag for NERSC jobs

### ISSUE THREAD

**Issue by StevenCTimm** [DUNE/dist-comp#193]
I had previously said that Desired_OS = SL7 should be set in all JustIN jobs that are bound for NERSC.
The actual correct name of the flag is DesiredOS.  Can this change please be made?

Thanks

Steven Timm

**Comment by Andrew-McNab-UK** [comment]
Thanks: this is changed on the main branch. It will be deployed on integration this week.

**Comment by StevenCTimm** [comment]
Tested it, there is still a problem:

It was set as
DesiredOS = SL7

in the classads, that would expect that there is either a htcondor macro or machine classad called SL7

What we really needed was 

DesiredOS = "SL7"

sorry I wasn't clear on that, please make the change.

**Comment by StevenCTimm** [comment]
This is done now... however there are other issues with the Justin-generated classads, I will open a new issue.
