### ISSUE TITLE
Plan and deploy DUNE global pool

### ISSUE THREAD

**Issue by StevenCTimm** [DUNE/dist-comp#2]

**Comment by StevenCTimm** [comment]
Internal testing currently under way by the Fermilab 
Compute Services Infrastructure group.

**Comment by Andrew-McNab-UK** [comment]
Service Now ticket about this: https://fermi.servicenowservices.com/wp/?id=evg-ticket&sys_id=5c845d831bc064104e1e0f21f54bcb79&table=sc_req_item

**Comment by Andrew-McNab-UK** [comment]
The tasks on us are to deploy schedds at BNL, RAL-PPD and CC-IN2P3 for local users or justIN (RAL-PPD) to make the Global Pool accessible offsite.

**Comment by StevenCTimm** [comment]
ST also wants to make such a schedd at CERN (in the cloud))

**Comment by StevenCTimm** [comment]
All done now except for the monitoring.
