### ISSUE TITLE
UNICAMP

### ISSUE THREAD

**Issue by StevenCTimm** [DUNE/dist-comp#20]
Greetings

I could not get a connection today and misedthe meeting and there is a 
point I wanted to bring to the meeting consideration.

UNICAMP is in a position to start adding their nodes to the DUNE computing
and needs help to itegrate their cluster to the DUNE system.

At the moment they have the following configuration available

hardware: 2 nodes (24 cores), 48 GB ram, network 40 GBit
these are for preliminary tests, it can be heavily improved
afterwards.

software:  CentOS 7, CVMFS, Torque(PBS-Pro)

Fábio Andrijauskas (fandri@ifi.unicamp.br)  is their HPC guru, the proper 
contact person for the hands-on  of the integration task.

Could he get the necesary help so we can advance in adding another 
Brazilain ite to the ytem?

Bet regard

Helio

**Comment by kherner** [comment]
Hi everyone,

I should have some time to work with Fabio this week. To begin, we would need to know the address of the CE So we can try to probe it.

**Comment by StevenCTimm** [comment]
From meeting today--worker nodes have access to internet via gateway node. 
Just have to figure out how to install htcondor-ce. should be on separate node from PBS master.

**Comment by StevenCTimm** [comment]
UNICAMP worked for a while but has now dropped off-line again due to loss of staff and we have heard from other colleagues that we should not expect it back.
