### ISSUE TITLE
overall dataset with --output-rse-expression Justin 1.0.2 not getting created.

### ISSUE THREAD

**Issue by StevenCTimm** [DUNE/dist-comp#205]
first indication that something is wrong in the above file is here:
[3:54](https://dunescience.slack.com/archives/C046XB7KAK1/p1732053245168059)
--- Rucio attach_dids test-01-w531s1p1 call fails: Data identifier not found.
Details: Data identifier 'testpro:test-01-w531s1p1' not found

NEW

[3:55](https://dunescience.slack.com/archives/C046XB7KAK1/p1732053349486869)
and it looks like this might have been the reason the dataset creation failed
[3:55](https://dunescience.slack.com/archives/C046XB7KAK1/p1732053350264829)
Traceback (most recent call last):
  File "/cvmfs/dune.opensciencegrid.org/products/dune/justin/int/NULL/jobutils/justin-job-datasets", line 140, in <module>
    createOneDataset(dataset)
  File "/cvmfs/dune.opensciencegrid.org/products/dune/justin/int/NULL/jobutils/justin-job-datasets", line 99, in createOneDataset
    lifetime = dataset['lifetime_seconds'])
KeyError: 'lifetime_seconds'

-------

it is this command that is failing:

Nov 19 20:15:07 Try 2/3 of executing these commands in a subshell: source /cvmfs/dune.opensciencegrid.org/products/dune/setup_dune.sh ; setup python v3_9_13 ; setup metacat ; setup rucio ; export X509_USER_PROXY=justin-jobs-production.proxy.pem ; export METACAT_AUTH_SERVER_URL=https://metac/
at.fnal.gov:8143/auth/dune ; export METACAT_SERVER_URL=https://metacat.fnal.gov:9443/dune_meta_prod/app ; metacat auth login -m x509 dunepro ; /cvmfs/dune.opensciencegrid.org/products/dune/justin/int/NULL/jobutils/justin-job-datasets

-----------

so now I have to find the datasets.json file that's getting fed to Justin-job-datasets and see what's wrong with that.  Like many other Justin debugging tasks this requires catching a job while it is running.

**Comment by StevenCTimm** [comment]
datasets.json looks like this

[{"metadata": {"dune.workflow": {"workflow_id": 534, "stage_id": 1, "pattern_id": 1, "file_pattern": "sha1sum-*.txt", "user": "timm@fnal.gov", "processors": 1, "rss_bytes": 2097152000, "wall_seconds": 80000, "jobscript_image": "/cvmfs/singularity.opensciencegrid.org/fermilab/fnal-wn-sl7:latest"}}, "dataset_scope": "testpro", "dataset_name": "w534s1p1-DUNE_US_BNL_SDCC", "rse_expression": "DUNE_US_BNL_SDCC", "lifetime_seconds": 604800}, {"metadata": {"dune.workflow": {"workflow_id": 534, "stage_id": 1, "pattern_id": 1, "file_pattern": "sha1sum-*.txt", "user": "timm@fnal.gov", "processors": 1, "rss_bytes": 2097152000, "wall_seconds": 80000, "jobscript_image": "/cvmfs/singularity.opensciencegrid.org/fermilab/fnal-wn-sl7:latest"}}, "dataset_scope": "testpro", "dataset_name": "test-01-w534s1p1n001", "rse_expression": "DUNE_US_FNAL_DISK_STAGE"}, {"metadata": {"dune.workflow": {"workflow_id": 534, "stage_id": 1, "pattern_id": 1, "file_pattern": "sha1sum-*.txt", "user": "timm@fnal.gov", "processors": 1, "rss_bytes": 2097152000, "wall_seconds": 80000, "jobscript_image": "/cvmfs/singularity.opensciencegrid.org/fermilab/fnal-wn-sl7:latest"}}, "dataset_scope": "testpro", "dataset_name": "test-01-w534s1p1"}]

**Comment by Andrew-McNab-UK** [comment]
This is believed to be fixed in 01.02.rc5

**Comment by StevenCTimm** [comment]
I can confirm that the datasets were all made and populated correctly in workflow 536, with the right rules.
I have a causality issue though because I had only 456 files in the workflow and should have had only 456 outputs
but I have 599 files in the output set.  That is not an issue with the implementation of this feature though so I will close this issue.
