### ISSUE TITLE
UK stashcache problems

### ISSUE THREAD

**Issue by Andrew-McNab-UK** [DUNE/dist-comp#25]
Low efficiency seen which turned out to be problems for sites using Cardiff stashcache instance. UK is proposing to create an instance at a GridPP site (ie an HEP site). Also looking at feasibility of changing cvmfs config to remove Cardiff for the time being.

**Comment by Andrew-McNab-UK** [comment]
Raja has now added a check of the stashcache external host in use for /cvmfs/dune.osgstorage.org on each worker node the DUNE ETF tests run on. In the output of the WN cvmfs test for each CE, you can see lines like this:

INFO: Attribute "external_host" had a 40 byte value for /cvmfs/dune.osgstorage.org: http://stashcache.gravity.cf.ac.uk:8000/

which are the result of executing 

attr -g external_host /cvmfs/dune.osgstorage.org

For a top level view of all sites see

https://etf-dune-preprod.cern.ch/etf/check_mk/index.py?start_url=%2Fetf%2Fcheck_mk%2Fview.py%3Fview_name%3Dallhosts

**Comment by StevenCTimm** [comment]
This is now solved by deployment of stashcache at Edinburgh
