### ISSUE TITLE
Access to FNAL dCache REST API end points from outside FNAL?

### ISSUE THREAD

**Issue by Andrew-McNab-UK** [DUNE/dist-comp#27]
This does not seem to be possible and yet is necessary to apply pins and check on their progress, or even that a file is ONLINE or not.

At FNAL, a connection is allowed but elsewhere the connection is refused:

echo | openssl s_client -connect fndca.fnal.gov:3880

**Comment by StevenCTimm** [comment]
I have made a query to the dCache developers about getting some documentation for this API and understanding what can/should be done.

**Comment by Andrew-McNab-UK** [comment]
I've been using Paul Millar's talk here:  

https://indico.cern.ch/event/1006673/contributions/4225445/attachments/2188118/3697487/bulk-request.pdf

which has a link to this more detailed document, which was enough get it working with requesting pins with lifetimes and checking that they have become available (but only from FNAL): 

https://docs.google.com/document/d/14sdrRmJts5JYBFKSvedKCxT1tcrWtWchR-PJhxdunT8/

**Comment by StevenCTimm** [comment]
OK I have talked to Dmitry..To open this port to off-site they would have to go through site computer security and request a web exemption, which they are willing to do.  I guess what I am missing is the bigger picture of
the file delivery workflow in the workflow allocator system.. what files are you pinning, and when.  Would like to understand the bigger picture and how it compares to what the data dispatcher is doing.  (guessing that that is using a legacy interface to dCache to do the staging).

**Comment by StevenCTimm** [comment]
Request has been filed
https://fermi.servicenowservices.com/nav_to.do?uri=%2Fsc_req_item.do%3Fsys_id%3D89b86e6adbdb0d1014c35425f39619a3%26sysparm_view%3Dess%26sysparm_record_target%3Dsc_req_item%26sysparm_record_row%3D12%26sysparm_record_rows%3D13%26sysparm_record_list%3Dactive%253Dtrue%255Erequest.requested_forDYNAMIC107a23f36f9c394032544d1fde3ee43b%255Erequest.requested_for%253D32b4c7270a0a3c590054cb9fd2a1c689%255EORrequest.requested_for.manager%253D32b4c7270a0a3c590054cb9fd2a1c689%255EORcat_item%2521%253D0366e9a11b3ae01084150e9ee54bcb86%255Eu_security_related%253Dfalse%255EORwatch_listCONTAINS32b4c7270a0a3c590054cb9fd2a1c689%255EORDERBYopened_by

RITM1401000

**Comment by StevenCTimm** [comment]
A new port was put up especially for off-site access and it is working.
