### ISSUE TITLE
Add GLIDEIN_DUNESite to new factory entries that take DUNE

### ISSUE THREAD

**Issue by StevenCTimm** [DUNE/dist-comp#29]
There are several factory entries which now support DUNE that didn't use to, which need a GLIDEIN_DUNESite.
Need to make a PR to the factory config repo to get this to happen.

**Comment by Andrew-McNab-UK** [comment]
Do we know if this is still the case, or can we close this issue?

**Comment by kherner** [comment]
As far as I'm aware we've updated everything. I suggest we close this issue and then open a new one if we find out anything slipped through the cracks.
