### ISSUE TITLE
cigetcert is still firewalled off from working off-site

### ISSUE THREAD

**Issue by StevenCTimm** [DUNE/dist-comp#32]
port 443 on jobsub servers still not available off-site.. can get a proxy manually and 
do what needs to be done but the setup is absolutely required.

**Comment by StevenCTimm** [comment]
This will shortly be moot because cigetcert will go away along with the jobsub server it was written for.

**Comment by Andrew-McNab-UK** [comment]
I think we can safely close this, for the reasons Steve says. (I originally asked about it.)
