### ISSUE TITLE
Onboard DURHAM as a DUNE site

### ISSUE THREAD

**Issue by StevenCTimm** [DUNE/dist-comp#38]
BOUTCHER, ADAM J. <adam.j.boutcher@durham.ac.uk>

To:Steven C Timm
Cc:CLARK, PAUL W.J. <paul.w.clark@durham.ac.uk>
Mon 1/30/2023 9:12 AM
Hi Steve,

I've been tasked with trying to support DUNE here at UKI-SCOTGRID-
DURHAM.

I've (hopefully) setup the VO to run on our CE3 and CE4 ARC CE's. If
there's anything specific that you require please let me know. And if
you could test out some submissions (if you wish to use us) then I'd be
really grateful for feedback etc.

Thanks
Adam

-- 
Adam Boutcher
Senior Technical Manager (IPPP Computing Service)
Institute for Particle Physics Phenomenology (IPPP)
OC216, Ogden Centre (East)
Durham University
South Road
Durham
DH1 3LE, United Kingdom

Tel: +44 (0)191 33 43527

Email: adam.j.boutcher@durham.ac.uk

**Comment by StevenCTimm** [comment]
I've responded to Adam asking for host names of their CE's once that is in hand we can open a ticket with the OSG to add to the factory.

**Comment by StevenCTimm** [comment]
Hi,

No worries.

ce3.dur.scotgrid.ac.uk
and
ce4.dur.scotgrid.ac.uk

We're an ARC CE site.

Let me know if you need any more details.


Adam

**Comment by kherner** [comment]
Looks like Durham doesn't have any existing entries for another VO in the factories, so this will be a new entry. In addition to the CE names, which we already have, we need

1) Number of cores and total memory for the glideins.
2) The RSL string needed to get to the proper queues with the requested resources
3) Names for GLIDEIN_Site, GLIDEIN_DUNESite, and GLIDEIN_ResourceName. For the latter we usually try to match the EGI name, if it exists. In this case it would be UKI-SCOTGRID-DURHAM. So I would just stick with that for GLIDEIN_ResourceName.  For the first two, how about simply UK_Durham? Or UK_DURHAM if all caps is preferred for some reason.

**Comment by Andrew-McNab-UK** [comment]
I think UK_Durham for the DUNE site name since it’s a place not an abbreviation.

**Comment by adamboutcher** [comment]
So these are what I proposed based on ECDF, however we're not too picky.

Glidein Site name = UK_SGridDurham
Glidein DUNE Site name = UK_SGridDurham
Glidein Resource name. = UKI-SCOTGRID-DURHAM
(Based on the EGI/GOCDB naming)

Number of cores per glidein = 1,2,4 or 8 (we'd prefer 8 but whatever works best for you really)
Max memory per glidein = 2 GB per core
Max run time of the glideins = 2 days

**Comment by kherner** [comment]
OK, thanks! I'll start a ticket with the OSG factory ops to get a new entry set up.

**Comment by StevenCTimm** [comment]
[https://support.opensciencegrid.org/support/tickets/public/09c832812acfca85656562fb832cb5fd1522af7279b24dda09e21d727d79c3e5](https://urldefense.proofpoint.com/v2/url?u=https-3A__support.opensciencegrid.org_support_tickets_public_09c832812acfca85656562fb832cb5fd1522af7279b24dda09e21d727d79c3e5&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=10BCTK25QMgkMYibLRbpYg&m=30ATUVwn9Qat-FlvrJsHNj0tb-T3OVs4WW6D_-hSMLfzXFcV5PZBlDQVFIU_tpqM&s=UKoS94GU0UhFiaCWs_dxiERwRuQGKND4XsCX30amL6A&e=)

That's the URL to the OSG ticket to get DURHAM into the factory

**Comment by StevenCTimm** [comment]
Factory reports that glideins are now starting at Durham.

**Comment by StevenCTimm** [comment]
Analysis shows that glideins are failing because they can't find singularity/apptainer.

**Comment by StevenCTimm** [comment]
Discussed in the ops meeting.. glideinwms should be smart enough to find the apptainer from CVMFS and apparently it is not doing so, we will have to investigate the factory log.

**Comment by StevenCTimm** [comment]
It worked briefly but then broke again this is tracked in #101
