### ISSUE TITLE
Tickets for sites failing ETF

### ISSUE THREAD

**Issue by rajanandakumar** [DUNE/dist-comp#41]
We need to create tickets for sites failing ETF tests.

https://etf-dune-prod.cern.ch/etf/check_mk/index.py?start_url=%2Fetf%2Fcheck_mk%2Fview.py%3Fview_name%3Dallhosts

It is not clear how to open tickets for most of the US sites failing in the above link.

Tickets already open : 

https://ggus.eu/index.php?mode=ticket_info&ticket_id=160588
https://ggus.eu/?mode=ticket_info&ticket_id=160352

Cheers,
Raja.

**Comment by StevenCTimm** [comment]
Tickets against US OSG sites should be filed through https://support.opensciencegrid.org through their Freshdesk system.  One of the worst ticketing systems ever yet invented.  Save your ticket number because you may not be able to search your own tickets, much less anyone else's.

**Comment by rajanandakumar** [comment]
Tickets opened likely due to non-updated VOMS DNs :

SARA : https://ggus.eu/index.php?mode=ticket_info&ticket_id=160690
NIKHEF : https://ggus.eu/index.php?mode=ticket_info&ticket_id=160689

**Comment by rajanandakumar** [comment]
@StevenCTimm NIKHEF point out that the rpm with new voms DNs contains the old version of voms2 DN. Could you have a look please. I am also adding your email as cc in the GGUS ticket.

**Comment by rajanandakumar** [comment]
GGUS Tickets opened for 

Brunel : https://ggus.eu/index.php?mode=ticket_info&ticket_id=160751
ECDF : https://ggus.eu/index.php?mode=ticket_info&ticket_id=160752

@StevenCTimm or @kherner need to open ticket against the pilot factory for : 
Removing the following CE :  hepgrid2.liv.ac.uk
Adding the following CE : hepgrid6.ph.liv.ac.uk.

**Comment by StevenCTimm** [comment]
All tickets mentioned above are resolved so we are closing this.

To be sure there are a lot of other ETF jobs failing because they are trying to run against sites that only take tokens now but that is covered in another ticket in this tracker.
