### ISSUE TITLE
UK Schedd doesn't see resources

### ISSUE THREAD

**Issue by cajbrew** [DUNE/dist-comp#44]
Running condor_status on the new UK Schedd doesn't see any resources other than the collector and the Schedd at BNL
```
# condor_status -any
MyType             TargetType         Name

Collector          None               DUNEGLOBAL@dunegpcoll01.fnal.gov
Scheduler          None               justin-prod-sched01.dune.hep.ac.uk
DaemonMaster       None               justin-prod-sched01.dune.hep.ac.uk
Scheduler          None               osgsub02.sdcc.bnl.gov
DaemonMaster       None               osgsub02.sdcc.bnl.gov
```

**Comment by StevenCTimm** [comment]
Chris--try

condor_status -any -pool dunegpcoll01.fnal.gov

By default you are configured to look at just dunegpcoll01.fnal.gov:9620 instead of the main collector dunegpcoll01.fnal.gov:9618

**Comment by cajbrew** [comment]
Yes, that's the problem. I can see all the resources now.
