### ISSUE TITLE
Add GLIDEIN_DUNESite to all dune sites in the factory

### ISSUE THREAD

**Issue by StevenCTimm** [DUNE/dist-comp#5]

**Comment by Andrew-McNab-UK** [comment]
OSG ticket: https://support.opensciencegrid.org/support/tickets/65249

PR: https://github.com/opensciencegrid/osg-gfactory/pull/6

Still waiting for the PR to be applied.

**Comment by Andrew-McNab-UK** [comment]
New PR after response from OSG: https://github.com/opensciencegrid/osg-gfactory/pull/7

**Comment by Andrew-McNab-UK** [comment]
No progress despite updating the OSG ticket asking for progress.

**Comment by StevenCTimm** [comment]
Finally done.. have verified all sites that support DUNE have a GLIDEIN_DUNEsite
