### ISSUE TITLE
Request Fermilab to support the DUNE ETF testing DN on gpce03/04 and cmsosgce*

### ISSUE THREAD

**Issue by StevenCTimm** [DUNE/dist-comp#6]

**Comment by StevenCTimm** [comment]
Right now  gpce03.fnal.gov and gpce04.fnal.gov don't actually support the DUNE VO because all DUNE submission at Fermilab is done locally through jobsub and doesn't glide in.  We can request that they do and they probably will.

**Comment by mhkirby** [comment]
REQ000000437120 has been opened to make this happen.

**Comment by StevenCTimm** [comment]
Fermilab has made gpce03/gpce04 now support DUNE.  Now we have to add DUNE support at the OSG factory 
so it will show up in the vofeed.xml

**Comment by StevenCTimm** [comment]
Ken will open a ticket to factory ops but we also have to block the gpfrontend01/02 to not send glideins there.

**Comment by StevenCTimm** [comment]
Ken has filed the ticket to the factory
ticket 65480
https://support.opensciencegrid.org/public/tickets/c85bd303d15dd5791a9f5be5e84a2c87268d2dcb91d1975b5fbd8e7cd3a72279

**Comment by StevenCTimm** [comment]
Factory entry is now in, now we have to modify the frontends at Fermilab so they don't request to it.
deny the site FNAL_GPGrid in the two frontend groups dune and dune_cern
Maybe merge dune and dune_cern while we are at it.

**Comment by StevenCTimm** [comment]
Frontends are now modified.  All we have to do is make a new vofeed.xml with FNAL_GPGrid in it.

**Comment by StevenCTimm** [comment]
ok now testing is ok on gpce03/04
Keep the ticket open, see if CMS Tier 1 will also let us run.

**Comment by rajanandakumar** [comment]
Not sure I understand. What are we watching for from CMS?

**Comment by StevenCTimm** [comment]
There are two clusters at Fermilab of roughly equal size, one called "FermiGrid" which is what we have been working on , which is behind gpce03/gpce04, and the other one is the CMS Tier 1.  There are rarely  many cycles available on the latter but most other Fermilab experiments do have opportunistic access to it.  At the moment DUNE does not, but we would like to get it.

**Comment by kherner** [comment]
I'll send a few test jobs to the FNAL T1 and force them to go there so that we have constant pressure until they run.

**Comment by StevenCTimm** [comment]
CMS Tier 1 (host cmsosgce-opp1) now supports DUNE jobs. But now the next step is to get it to take 
the DUNE ETF tokens as well (which now exist, as of today).

**Comment by StevenCTimm** [comment]
This was completed some time ago .
