### ISSUE TITLE
Contact US_Clemson to see if they will re-enable DUNE support

### ISSUE THREAD

**Issue by StevenCTimm** [DUNE/dist-comp#68]
They disabled DUNE when they went to a new hosted-CE.

**Comment by kherner** [comment]
Opened ticket 72792 with the OSG factory ops folks and copied the Clemson site admin. [Public link](https://support.opensciencegrid.org/support/tickets/public/71197cf246e7e01bda16785c034ebc49cf96fbb82f3e3f6cb02a69823d1ecde6)

**Comment by StevenCTimm** [comment]
Didn't hear back from them yet but Ken reports we ran something at Clemson.

**Comment by StevenCTimm** [comment]
We believe the problem is the site name that's being requested, Clemson vs. Clemson-Palmetto
Will investigate further.

**Comment by StevenCTimm** [comment]
Now tracked in #97
