### ISSUE TITLE
UChicago (Midwest tier 2) why did they drop DUNE

### ISSUE THREAD

**Issue by StevenCTimm** [DUNE/dist-comp#70]
and can we get them to take us back.

**Comment by StevenCTimm** [comment]
Ken made remarks in today's meeting that in the days when they did take dune they had only a 6 hour time limit on opportunistic jobs, our jobs and other VOs too.

**Comment by kherner** [comment]
We've been re-added as a supported VO, so we should start seeing some things there pretty soon. The max glidein wall time is now 12 hours according to the factory entry.

**Comment by kherner** [comment]
Well shoot: we've got pilots, but they're all held. Probably an auth issue. Here the public link for the ticket: [https://support.opensciencegrid.org/support/tickets/public/2814ae7411f986c7f533402c0e26c4d064faccec5d6f73d14230ee466f2a7558](https://support.opensciencegrid.org/support/tickets/public/2814ae7411f986c7f533402c0e26c4d064faccec5d6f73d14230ee466f2a7558)

**Comment by StevenCTimm** [comment]
Note that we (CSI group) can now query the factory ourselves and save an OSG ticket if needed.  The error in this case is:

Engage_US_MWT2_iut2_condce ERROR: Failed to submit job.

**Comment by kherner** [comment]
I'm discussing with them on the OSG Slack now; looks like a local user account mapping issue.

**Comment by StevenCTimm** [comment]
back now, but not added to the Justin yet.
