### ISSUE TITLE
Get factory limit set to 4096MB for Manchester entries

### ISSUE THREAD

**Issue by StevenCTimm** [DUNE/dist-comp#85]
currently unset and defaulting to 1 MB

**Comment by Andrew-McNab-UK** [comment]
4096MB in the factory config please not 4000. We have 4096/cpu in the local HTCondor config.

**Comment by StevenCTimm** [comment]
OSG ticket is filed.

**Comment by StevenCTimm** [comment]
May have to do this for Edinburgh too

**Comment by Andrew-McNab-UK** [comment]
73997 apparently (I can't view OSG tickets unless I get the email, I think)

**Comment by StevenCTimm** [comment]
This has been done and jobs are running OK at Manchester again.
